name: Create and publish binaries

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Building for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-libc-dev
      - name: Make
        shell: bash
        run: |
          export _XOPEN_SOURCE=y
          make
      - name: Create release archive
        shell: bash
        run: |
          tar -czvf wrapped-kmc-gcc-${{ matrix.os }}.tar.gz as cc1 cpp gcc mild makemask sgi2gas ld
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: wrapped-kmc-gcc-${{ matrix.os }}
          path: |
            wrapped-kmc-gcc-${{ matrix.os }}.tar.gz
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: wrapped-kmc-gcc-${{ matrix.os }}.tar.gz
